# Generated by Django 5.0 on 2023-12-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='list/images/'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='list/images/'),
        ),
    ]
