# Generated by Django 5.0 on 2023-12-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todoitem_icon_alter_todolist_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='color',
            field=models.CharField(blank=True, choices=[('Red', 'red'), ('Blue', 'blue'), ('Green', 'green'), ('yellow', 'yellow'), ('purple', 'purple'), ('orange', 'orange'), ('brown', 'brown'), ('pink', 'pink'), ('aqua', 'aqua'), ('white', 'white')], max_length=20),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='color',
            field=models.CharField(blank=True, choices=[('Red', 'red'), ('Blue', 'blue'), ('Green', 'green'), ('yellow', 'yellow'), ('purple', 'purple'), ('orange', 'orange'), ('brown', 'brown'), ('pink', 'pink'), ('aqua', 'aqua'), ('white', 'white')], max_length=20),
        ),
    ]
