# Generated by Django 5.0 on 2023-12-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todoitem_color_alter_todolist_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='sender',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'yellow'), ('purple', 'purple'), ('orange', 'orange'), ('brown', 'brown'), ('pink', 'pink'), ('aqua', 'aqua'), ('white', 'white')], max_length=20),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'yellow'), ('purple', 'purple'), ('orange', 'orange'), ('brown', 'brown'), ('pink', 'pink'), ('aqua', 'aqua'), ('white', 'white')], max_length=20),
        ),
    ]
